apiVersion: v1
data:
  DB_PASSWORD: YXBwdXNlcg==
  DB_USER: YXBwdXNlcg==
  password: YXBwdXNlcg==
  postgres-password: YWRtaW4xMjM0
kind: Secret
metadata:
  name: order-backend-secret
  namespace: my-tech
