secret:
  create: true
  name: order-backend-secret

db:
  fullnameOverride: db-postgresql
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "17"
  auth:
    existingSecret: order-backend-secret
    username: orders_user
    password: supersecret
    postgresPassword: adminsecret
    database: ordersdb
  primary:
    persistence:
      enabled: true
      size: 1Gi

backend:
  image:
    repository: docker.io/eduardoalvear/order-app
    tag: "1.0.3"
    pullPolicy: IfNotPresent
  replicaCount: 2
  resources:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  host: order.local
  config:
    DB_HOST: db-postgresql.my-tech.svc.cluster.local
    DB_PORT: "5432"
    DB_NAME: ordersdb
  secretName: order-backend-secret

resources:
  requests: { cpu: "200m", memory: "256Mi" }
  limits:   { cpu: "500m", memory: "512Mi" }
