apiVersion: v1
kind: ConfigMap
metadata:
  name: order-backend-config
  namespace: my-tech
data:
  DB_HOST: {{ .Values.backend.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.backend.config.DB_NAME | quote }}