apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-backend-ing
  namespace: my-tech
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: order.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: order-backend-svc
                port:
                  number: 8080
