{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # Para Bitnami (existingSecret) y para el backend
  username: {{ .Values.db.auth.username | quote }}
  password: {{ .Values.db.auth.password | quote }}
  postgres-password: {{ .Values.db.auth.postgresPassword | quote }}
  database: {{ .Values.db.auth.database | quote }}
{{- end }}
