apiVersion: v1
kind: Service
metadata:
  name: order-backend-svc
  namespace: my-tech
spec:
  selector:
    app: order-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP